language: cpp

git:
  depth: false #shallow clone causes problem with tags
  
addons:
  apt:
    update: true

os:
  - linux
 # - osx
  
compiler:
  - gcc
#  - clang
  
env:
#  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug
  
  
branches:
  only:
    - develop
    - master
    - CIDev
    - /^release\/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*$/

dist: xenial    #ubuntu
    
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  
install:
    - mkdir -p build/install && cd build
    - export INSTALL_PREFIX=$(pwd)/install
  #- sudo apt-get install g++ 
  #- sudo apt-get install gcc
  # boost1.55 libgtest-dev libsnappy-dev
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc
  # - "cd /usr/src/gtest && sudo cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  
before_script:
  
  
script: 
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIG -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
  - make
  - make install
  - ls install
  - install/test/libkafka_asio_test
