version: AppVeyorBuild-{build}
branches:
  only:
  - develop
  - master
  - CIDev
  - /^release\/.*$/
  - /^[0-9]+\.[0-9]+\.[0-9]+.*$/
  
os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration:
  - Release
  - Debug

environment:
  matrix:
    - platform: Win32
      cpu_bits: 32
      cmake_builddir: build-win32
    - platform: x64
      cpu_bits: 64
      cmake_builddir: build-win64
 
clone_folder: C:\projects\libkafka-asio
  
init:
    
install:
 
cache:

before_build:
- cmd: cd C:\projects\libkafka-asio
- ps: >-
        If ($env:Platform -Match "64") {
            $env:GEN_PLAT=" Win64"
        } Else {
            $env:GEN_PLAT=""
        }
- cmd: 'cmake . -B%cmake_builddir% -G"Visual Studio 15 2017%GEN_PLAT%" -DCMAKE_CONFIGURATION_TYPES=%configuration%  '

#build:
#  parallel: true                  # enable MSBuild parallel builds
#  project: build-win32\libkafka-asio_suite.sln      # path to Visual Studio solution or project

build_script:
- cmd: cmake --build %cmake_builddir% --config %configuration%
- cmd: cmake --build %cmake_builddir% --config %configuration% --target PACKAGE

test_script:
- cmd: '%cmake_builddir%\%configuration%\libkafka_asio_tests.exe'

artifacts:
  - path: $(cmake_builddir)\libkafka-asio-*.*.*-*-*-*-*-*.exe
    name: Releases

deploy:
  release: 'libkafka-asio $(APPVEYOR_REPO_TAG_NAME)'
  description: ''
  provider: GitHub
  auth_token:
    secure: MuDZnJV9gGH51bmihPpcFDEyAVC3bU9BPaciSz48OI3sZfe1j4Y7BaMLV4qJqwIC
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true


